version: '3'

volumes:
    logs:
        driver: local

services:
    db:
        image: mysql:5.7
        restart: always
        ports:
            - 3306:3306
        volumes:
            - .docker/mysql/:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=public
        command: --sql_mode="NO_ENGINE_SUBSTITUTION"
